# Generated by Django 5.2.9 on 2025-12-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='pin',
            field=models.CharField(blank=True, help_text='PIN para confirmar conexión desde el panel', max_length=10, null=True),
        ),
    ]
