# Generated by Django 5.2.9 on 2025-12-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cliente_pin'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_camera', models.CharField(blank=True, help_text='Stream key de la cámara actualmente al aire', max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
