# Generated by Django 5.2.9 on 2025-12-14 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_broadcaststate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Camera',
        ),
    ]
