# Generated by Django 5.2.9 on 2025-12-15 00:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_streamconnection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamconnection',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('ready', 'Lista'), ('on_air', 'Al aire')], default='pending', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='streamconnection',
            unique_together={('user', 'cam_index')},
        ),
    ]
