# Generated by Django 5.2.9 on 2025-12-15 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_streamconnection_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streamconnection',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='streamconnection',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('ready', 'Lista'), ('on_air', 'Al aire')], max_length=10),
        ),
    ]
