# Generated by Django 5.2.9 on 2025-12-22 16:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_streamconnection_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BroadcastState',
        ),
        migrations.RemoveField(
            model_name='streamconnection',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='streamconnection',
            name='connected_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='streamconnection',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('ready', 'Lista'), ('on_air', 'Al aire'), ('offline', 'Desconectada')], default='pending', max_length=10),
        ),
    ]
