# Generated by Django 5.2.9 on 2025-12-26 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_delete_broadcaststate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streamconnection',
            name='connected_at',
        ),
        migrations.AddField(
            model_name='streamconnection',
            name='conectado_en',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 12, 26, 17, 21, 51, 259546, tzinfo=datetime.timezone.utc), help_text='Momento en que nginx detectó la conexión RTMP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='streamconnection',
            name='ultimo_contacto',
            field=models.DateTimeField(auto_now=True, help_text='Última señal recibida desde nginx RTMP'),
        ),
    ]
