# Generated by Django 6.0 on 2025-12-28 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_delete_broadcaststate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Biografía'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='discord',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='facebook',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='instagram',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tiktok',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='x_twitter',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='youtube',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
