# Generated by Django 6.0 on 2025-12-29 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_cliente_bio_cliente_discord_cliente_facebook_and_more'),
        ('core', '0010_remove_streamconnection_connected_at_and_more'),
    ]

    operations = [
    ]
