# Generated by Django 5.2.9 on 2025-12-28 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_streamconnection_connected_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CanalTransmision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_vivo', models.BooleanField(default=False)),
                ('url_hls', models.CharField(blank=True, help_text='URL HLS pública del stream final', max_length=255)),
                ('inicio_transmision', models.DateTimeField(blank=True, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='canal_transmision', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
