# Generated by Django 6.0 on 2025-12-29 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_merge_20251228_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='pref_autoplay',
            field=models.BooleanField(default=True, verbose_name='Reproducción Automática'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='pref_emails',
            field=models.BooleanField(default=True, verbose_name='Recibir notificaciones por correo'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='pref_modo_teatro',
            field=models.BooleanField(default=False, verbose_name='Modo Teatro por defecto'),
        ),
    ]
