# Generated by Django 6.0 on 2025-12-29 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_cliente_pref_autoplay_cliente_pref_emails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='notif_chat_mentions',
            field=models.BooleanField(default=True, verbose_name='Menciones en Chat'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='notif_live',
            field=models.BooleanField(default=True, verbose_name='Alerta de Transmisión'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='notif_marketing',
            field=models.BooleanField(default=False, verbose_name='Novedades y Ofertas'),
        ),
    ]
