# Generated by Django 6.0 on 2025-12-31 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_canaltransmision'),
        ('core', '0013_cliente_notif_chat_mentions_cliente_notif_live_and_more'),
    ]

    operations = [
    ]
