# Generated by Django 6.0 on 2026-01-31 20:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_merge_20251231_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamconnection',
            name='ultimo_contacto',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Última señal recibida desde nginx RTMP'),
        ),
    ]
