# Generated by Django 6.0 on 2026-02-27 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_streamconnection_ultimo_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='canaltransmision',
            name='modo_radio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='canaltransmision',
            name='radio_imagen_path',
            field=models.CharField(blank=True, default='', help_text='Ruta absoluta a imagen JPG. Vacío = usar RADIO_IMAGE_PATH de settings.', max_length=500),
        ),
        migrations.AlterField(
            model_name='streamconnection',
            name='ultimo_contacto',
            field=models.DateTimeField(auto_now=True, help_text='Última señal recibida desde nginx RTMP'),
        ),
    ]
