# Generated by Django 6.0 on 2026-03-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_canaltransmision_modo_radio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='dominio',
            field=models.CharField(blank=True, max_length=253, null=True, unique=True),
        ),
    ]
