# Generated by Django 6.0 on 2026-01-22 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaYouTube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_transmision', models.CharField(help_text='Clave RTMP de la plataforma', max_length=200)),
                ('url_ingestion', models.CharField(help_text='URL base para ingestión RTMP', max_length=255)),
                ('activo', models.BooleanField(default=True, help_text='Si la cuenta está habilitada para retransmisión')),
                ('id_canal', models.CharField(help_text='ID único del canal de YouTube', max_length=100, unique=True)),
                ('nombre_canal', models.CharField(blank=True, help_text='Nombre público del canal', max_length=200)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
