# Generated by Django 6.0 on 2026-01-23 17:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multistream', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuentayoutube',
            options={'verbose_name': 'Cuenta YouTube', 'verbose_name_plural': 'Cuentas YouTube'},
        ),
        migrations.AddField(
            model_name='cuentayoutube',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cuentayoutube',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cuentayoutube',
            name='id_canal',
            field=models.CharField(blank=True, help_text='ID único del canal de YouTube', max_length=100),
        ),
        migrations.CreateModel(
            name='EstadoRetransmision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataforma', models.CharField(choices=[('youtube', 'YouTube'), ('facebook', 'Facebook'), ('twitch', 'Twitch'), ('instagram', 'Instagram')], max_length=20)),
                ('estado', models.CharField(choices=[('iniciando', 'Iniciando'), ('activo', 'Activo'), ('error', 'Error'), ('detenido', 'Detenido')], default='iniciando', max_length=20)),
                ('proceso_id', models.IntegerField(blank=True, help_text='PID del proceso FFmpeg', null=True)),
                ('iniciado_en', models.DateTimeField(auto_now_add=True)),
                ('detenido_en', models.DateTimeField(blank=True, null=True)),
                ('mensaje_error', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retransmisiones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estado de Retransmisión',
                'verbose_name_plural': 'Estados de Retransmisión',
                'ordering': ['-iniciado_en'],
            },
        ),
    ]
