# Generated by Django 6.0 on 2026-01-27 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multistream', '0002_alter_cuentayoutube_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaFacebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_transmision', models.CharField(help_text='Clave RTMP de la plataforma', max_length=200)),
                ('url_ingestion', models.CharField(help_text='URL base para ingestión RTMP', max_length=255)),
                ('activo', models.BooleanField(default=True, help_text='Si la cuenta está habilitada para retransmisión')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('id_pagina', models.CharField(blank=True, help_text='ID único de la página de Facebook', max_length=100)),
                ('nombre_pagina', models.CharField(blank=True, help_text='Nombre público de la página', max_length=200)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cuenta Facebook',
                'verbose_name_plural': 'Cuentas Facebook',
            },
        ),
    ]
